### ISSUE TITLE
Travis Builds

### ISSUE THREAD

**Issue by tresf** [andrewrk/libsoundio#61]
**Edit:**  it appears the task of getting Travis working for Linux build is going to prove very difficult to pull off due to the GCC 4.9 requirement, the changes in the dependent APIs combined with the age of the Travis build environments.

> andrewrk: "This is the conclusion I came to as well. I'm not in a rush to get Travis integration, but if in a year or two everybody finally updates their old systems and it becomes easy to turn them on, then sure, let's do it."

The following `yaml` still suffers from #7.

```yaml
sudo: required
 # Needed for newer ALSA
dist: trusty
language: c
compiler: gcc
before_install:
# Needed for newer GCC
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -qq update
    - sudo apt-get -qq install -y gcc-4.9
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/gcc-4.9 60
install:
    - sudo apt-get -qq install -y cmake libjack-dev libpulse-dev libasound2-dev
before_script:
    - mkdir build && cd build
script:
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make -j4
    - ./unit_tests
```

---

#49 mentions enabling travis.

In an attempt to simply get `gcc-4.9` working (which seems to be a hard-requirement of the atomic portions of the codebase), I'm not having any luck.

Here are my failed attempts:
https://github.com/tresf/libsoundio/commits/travis

And here's an example of a failed build:
https://travis-ci.org/tresf/libsoundio/builds/114152039

If @andrewrk in still in favor of the idea, we can use this bug report as a way to discuss the requirements for travis builds.
